POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQHRlc3QudGVzdCIsImV4cCI6MTc0MTg3NTAzNywidXNlcklkIjoxfQ.mlotQ1RyobrHI_jk5dMaHxlmdfpujN7DIec2UYRwauw

{
    "Name": "Test event 4",
    "description": "4 descrierea este aceasta",
    "location": "4 test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}