POST http://localhost:8080/cars
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q0QHRlc3QudGVzdCIsImV4cCI6MTc0NDEyNzYwMiwidXNlcklkIjoxfQ.5AjyfarMPqHdYy1ERTvQWbZmNzaR3M1ds3ARmxFeIB4

{
    "Make": "Mercedes",     
	"Model": "E",    
	"Year": 2013,    
	"Location": "Oradea",
	"Price": 310
}