GET http://localhost:8080/cars?make=Mercedes&location=Oradea&page=1&pageSize=2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQHRlc3QudGVzdCIsImV4cCI6MTc0NDExNTA1OSwidXNlcklkIjozfQ.0jnxRHvw1jbJKqWVubEozKUjYJGljRf__ed0tpYZ2Gc
