GET http://localhost:8080/cars?make=Mercedes&location=Oradea&page=1&pageSize=2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q0QHRlc3QudGVzdCIsImV4cCI6MTc0NDEyNzYwMiwidXNlcklkIjoxfQ.5AjyfarMPqHdYy1ERTvQWbZmNzaR3M1ds3ARmxFeIB4
